/**
 * ONE ENTRY OF EACH OF THE SEVENTY-ONE TYPES, in catalogue order, as a journal
 * that actually holds together: the campaign is created before anyone joins,
 * the character exists before their gauge moves, the track exists before it is
 * ticked.
 *
 * It is the fixture the reducer test replays. A journal that covered the types
 * without ordering them would let a branch look exercised while it silently
 * took the "unknown identifier" path of `withCharacter` and did nothing.
 *
 * It is a `.test.ts` because the flat ESLint config parses nothing else under
 * `tests/`, and because a fixture this load-bearing owes its readers a check
 * that it still covers what it claims. Reported with the task.
 */

import { FIXTURE_ATTRIBUTES, FIXTURE_GAUGES, anEvent, anId, fixtureCreatedAt } from '@for/testkit';
import { describe, expect, it } from 'vitest';

import type { GameEvent } from '../../src/index.js';
import { GAME_EVENT_TYPES } from '../../src/index.js';

export const CAMPAIGN = anId('campaign');
export const OWNER = anId('player');
export const GUEST = anId('player', 2);
export const HERO = anId('character');
export const TRACK = anId('track');
export const CLOCK = anId('clock');
export const ENTITY = anId('entity');
export const SCENE = anId('scene');
export const SESSION = anId('session');
export const CHRONICLE = anId('chronicle');
export const AI_CALL = anId('aicall');
export const PROPOSAL = anId('proposal');
export const ROLL = anId('roll');

type Entry = Omit<GameEvent, 'id' | 'campaignId' | 'seq' | 'createdAt' | 'correlationId'> & {
  readonly correlationId?: string | null;
};

/**
 * The payloads, in catalogue order. `seq`, `id` and `createdAt` are filled by
 * `everyEventJournal()` so the journal is dense by construction.
 */
const ENTRIES: readonly Entry[] = [
  {
    type: 'campaign.created',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      name: 'La Griffe d hiver',
      slug: 'griffe-d-hiver',
      pitch: 'Une bande remonte vers le nord.',
      ownerPlayerId: OWNER,
      contentPackVersion: '1.0.0',
      contentPackHash: 'sha256:content',
      rulesVersion: 1,
      rngSeed: 'seed-of-the-campaign',
    },
  },
  {
    type: 'campaign.truth_set',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { truthId: 'le-froid', optionId: 'le-froid-tue' },
  },
  {
    type: 'campaign.settings_updated',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { patch: { gmVerbosity: 'ample', oracleBias: undefined }, before: {} },
  },
  {
    type: 'campaign.status_changed',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { from: 'draft', to: 'active' },
  },
  {
    type: 'campaign.content_pack_changed',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      fromVersion: '1.0.0',
      fromHash: 'sha256:content',
      toVersion: '1.1.0',
      toHash: 'sha256:content-next',
      note: 'correctif de contenu',
    },
  },
  {
    type: 'party.member_joined',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { playerId: OWNER, role: 'owner', displayName: 'Kevin' },
  },
  {
    type: 'party.member_left',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { playerId: GUEST, reason: 'left' },
  },
  {
    type: 'party.member_role_changed',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { playerId: OWNER, from: 'player', to: 'owner' },
  },
  {
    type: 'party.champion_locked',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { championId: 'sejuani', lockKind: 'reserved_pc', reason: 'prise' },
  },
  {
    type: 'party.champion_unlocked',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { championId: 'sejuani', reason: 'liberee' },
  },
  {
    type: 'character.created',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      characterId: HERO,
      playerId: OWNER,
      championId: 'ashe',
      displayName: 'Ashe',
      sheetSource: 'handwritten',
      sheetRef: 'content:champions/ashe@1.0.0',
      sheetSnapshot: {},
      attributes: FIXTURE_ATTRIBUTES,
      gauges: FIXTURE_GAUGES,
      momentum: 2,
    },
  },
  {
    type: 'character.renamed',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, from: 'Ashe', to: 'Ashe la Flechiere' },
  },
  {
    type: 'character.gauge_changed',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      characterId: HERO,
      gauge: 'vigueur',
      delta: -2,
      from: 5,
      to: 3,
      clamped: false,
      cause: 'move:strike/echec',
    },
  },
  {
    type: 'character.momentum_changed',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      characterId: HERO,
      delta: 3,
      from: 2,
      to: 5,
      clamped: false,
      cause: 'effect:momentum',
    },
  },
  {
    type: 'character.momentum_burned',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, spent: 5, resetTo: 2, appliedToRollSeq: 1 },
  },
  {
    type: 'character.momentum_negated',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, actionDie: 2, momentumValue: -2, rollSeq: 1 },
  },
  {
    type: 'character.condition_added',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, conditionId: 'trouble', label: 'Trouble', source: 'engine' },
  },
  {
    type: 'character.condition_removed',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, conditionId: 'trouble', cause: 'effect:condition_remove' },
  },
  {
    type: 'character.asset_added',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, assetId: 'arc-de-givre' },
  },
  {
    type: 'character.asset_upgraded',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, assetId: 'arc-de-givre', abilityIndex: 1, xpCost: 3 },
  },
  {
    type: 'character.asset_removed',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, assetId: 'arc-de-givre', cause: 'price:d12=9' },
  },
  {
    type: 'character.xp_earned',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, amount: 2, reason: 'effect:xp', trackId: TRACK },
  },
  {
    type: 'character.xp_spent',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, amount: 1, target: 'arc-de-givre' },
  },
  {
    type: 'character.attributes_corrected',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      characterId: HERO,
      from: FIXTURE_ATTRIBUTES,
      to: { vif: 3, coeur: 2, fer: 2, ombre: 1, esprit: 1 },
      reason: 'saisie',
    },
  },
  {
    type: 'character.died',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, cause: 'move:endure-harm/echec' },
  },
  {
    type: 'character.retired',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { characterId: HERO, reason: 'la bande rentre' },
  },
  {
    type: 'character.sheet_rebound',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      characterId: HERO,
      fromSheetRef: 'content:champions/ashe@1.0.0',
      toSheetRef: 'content:champions/ashe@1.1.0',
      reason: 'montee de contenu',
    },
  },
  {
    type: 'roll.action_resolved',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: 'action',
    rngDrawIndex: 0,
    scope: 'table',
    recipients: null,
    payload: {
      rollId: ROLL,
      characterId: HERO,
      moveId: 'face-danger',
      attribute: 'fer',
      attributeValue: 2,
      actionDie: 4,
      adds: [],
      rawTotal: 6,
      total: 6,
      cappedAtTen: false,
      challengeDice: [3, 8],
      outcome: 'partielle',
      isPresage: false,
      momentumBefore: 2,
      momentumNegated: false,
      burnWindow: false,
      rngStream: 'action',
      rngDrawIndex: 0,
    },
  },
  {
    type: 'roll.action_revised',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { rollId: ROLL, revisedFromSeq: 28, total: 9, outcome: 'franche', isPresage: false },
  },
  {
    type: 'roll.progress_resolved',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: 'action',
    rngDrawIndex: 1,
    scope: 'table',
    recipients: null,
    payload: {
      rollId: ROLL,
      trackId: TRACK,
      ticks: 12,
      filledBoxes: 3,
      challengeDice: [2, 9],
      outcome: 'partielle',
      isPresage: false,
    },
  },
  {
    type: 'roll.oracle_resolved',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: 'oracle',
    rngDrawIndex: 0,
    scope: 'table',
    recipients: null,
    payload: {
      rollId: ROLL,
      tableId: 'complication',
      tableVersion: '1.0.0',
      dieSize: 6,
      value: 2,
      entryId: 'c1',
      text: 'une piste se perd',
      tags: [],
    },
  },
  {
    type: 'roll.yes_no_resolved',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: 'oracle',
    rngDrawIndex: 1,
    scope: 'table',
    recipients: null,
    payload: {
      rollId: ROLL,
      question: 'Le pont tient-il ?',
      likelihood: 'incertain',
      threshold: 50,
      value: 12,
      answer: 'oui',
      isExtreme: false,
    },
  },
  {
    type: 'roll.price_paid',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: 'price',
    rngDrawIndex: 0,
    scope: 'table',
    recipients: null,
    payload: {
      rollId: ROLL,
      value: 7,
      entryId: 'p7',
      text: 'le froid prend sa part',
      severity: 'moyenne',
      effectIndex: 0,
    },
  },
  {
    type: 'roll.presage_drawn',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: 'presage',
    rngDrawIndex: 0,
    scope: 'table',
    recipients: null,
    payload: {
      rollId: ROLL,
      tableId: 'presages',
      value: 4,
      entryId: 'pr2',
      text: 'la glace craque',
      triggeredByRollSeq: 28,
    },
  },
  {
    type: 'roll.raw',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { rollId: ROLL, label: 'd6', dice: [{ sides: 6, value: 3 }], reason: 'demo' },
  },
  {
    type: 'move.declared',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      moveId: 'face-danger',
      characterId: HERO,
      narrativeInput: 'je saute',
      chosenAttribute: 'fer',
    },
  },
  {
    type: 'move.resolved',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      moveId: 'face-danger',
      characterId: HERO,
      rollSeq: 28,
      outcome: 'partielle',
      effectsApplied: [],
    },
  },
  {
    type: 'move.aborted',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { moveId: 'face-danger', characterId: HERO, reason: 'gm_refusal:cible_absente' },
  },
  {
    type: 'track.created',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      trackId: TRACK,
      kind: 'vow',
      rank: 'dangereux',
      title: 'Ramener la corne',
      description: '',
      ownerCharacterId: HERO,
      visibility: 'public',
      initialTicks: 0,
    },
  },
  {
    type: 'track.ticked',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      trackId: TRACK,
      ticks: 8,
      from: 0,
      to: 8,
      cause: 'effect:track_tick',
      milestones: 1,
    },
  },
  {
    type: 'track.rank_changed',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { trackId: TRACK, from: 'dangereux', to: 'redoutable', reason: 'la traque se durcit' },
  },
  {
    type: 'track.resolved',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { trackId: TRACK, outcome: 'fulfilled', rollSeq: 30, xpAwarded: 2 },
  },
  {
    type: 'track.forsaken',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { trackId: TRACK, reason: 'le serment tombe', xpLost: 1 },
  },
  {
    type: 'track.abandoned',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { trackId: TRACK, reason: 'menage' },
  },
  {
    type: 'clock.created',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      clockId: CLOCK,
      title: 'La tempete se leve',
      description: '',
      segments: 4,
      visibility: 'public',
      consequence: 'Le col se ferme.',
    },
  },
  {
    type: 'clock.advanced',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { clockId: CLOCK, delta: 2, from: 0, to: 2, cause: 'effect:clock_advance' },
  },
  {
    type: 'clock.filled',
    actorKind: 'engine',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { clockId: CLOCK, consequence: 'Le col se ferme.' },
  },
  {
    type: 'clock.resolved',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { clockId: CLOCK, resolution: 'la bande a passe le col' },
  },
  {
    type: 'clock.cancelled',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { clockId: CLOCK, reason: 'sans objet' },
  },
  {
    type: 'scene.started',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      sceneId: SCENE,
      title: 'Le col des Hurleurs',
      regionId: 'freljord',
      entityIds: [ENTITY],
      presentCharacterIds: [HERO],
    },
  },
  {
    type: 'scene.ended',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { sceneId: SCENE, outcome: 'la bande passe' },
  },
  {
    type: 'scene.facts_updated',
    actorKind: 'gm_ai',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      sceneId: SCENE,
      placeId: 'col-des-hurleurs',
      placeName: 'Le col des Hurleurs',
      timeOfDay: 'fin de journee',
      present: [
        { ref: { kind: 'character', id: HERO }, name: 'Ashe', state: 'debout', sinceSeq: 1 },
      ],
      absent: [],
      source: 'gm_ai',
      aiCallId: AI_CALL,
    },
  },
  {
    type: 'narration.player_message',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: HERO,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { text: 'Je tends la corde.', kind: 'ic', characterId: HERO },
  },
  {
    type: 'narration.gm_message',
    actorKind: 'gm_ai',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      text: 'La corde tient.',
      aiCallId: AI_CALL,
      model: 'stub',
      promptVersion: 'conteur/2.0.0',
      source: 'ai',
      citedEventSeqs: [],
    },
  },
  {
    type: 'narration.gm_failed',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { errorKind: 'api_error', fallbackText: 'Le froid entre en toi.' },
  },
  {
    type: 'narration.gm_proposal',
    actorKind: 'gm_ai',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { proposalId: PROPOSAL, kind: 'entity', payload: { slug: 'katla' } },
  },
  {
    type: 'narration.proposal_accepted',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { proposalId: PROPOSAL, resultingEventSeqs: [] },
  },
  {
    type: 'narration.proposal_rejected',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { proposalId: PROPOSAL, reasonCode: 'name_taken', validationErrors: [] },
  },
  {
    type: 'narration.safety_flag',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { kind: 'veil' },
  },
  {
    type: 'entity.introduced',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      entityId: ENTITY,
      kind: 'npc',
      slug: 'katla',
      name: 'Katla',
      summary: 'Une eclaireuse avarosane.',
      details: { arme: 'hache' },
    },
  },
  {
    type: 'entity.updated',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      entityId: ENTITY,
      patch: { summary: 'Une eclaireuse blessee.', arme: 'hache brisee' },
      before: { summary: 'Une eclaireuse avarosane.' },
    },
  },
  {
    type: 'entity.status_changed',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { entityId: ENTITY, from: 'active', to: 'dormant', cause: 'scene:end' },
  },
  {
    type: 'entity.mentioned',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { entityId: ENTITY },
  },
  {
    type: 'session.opened',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: SESSION,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { playSessionId: SESSION, ordinal: 1, presentPlayerIds: [OWNER] },
  },
  {
    type: 'session.closed',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: SESSION,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { playSessionId: SESSION, firstSeq: 1, lastSeq: 66 },
  },
  {
    type: 'chronicle.compacted',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      chronicleId: CHRONICLE,
      version: 1,
      kind: 'incremental',
      sourceEventSeq: 66,
      aiCallId: AI_CALL,
      tokenCount: 900,
    },
  },
  {
    type: 'system.reverted',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { targetSeqs: [], reason: 'gm_refusal:cible_absente', byPlayerId: null },
  },
  {
    type: 'system.correction',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: {
      targetSeq: 12,
      field: `entities.${ENTITY}.name`,
      from: 'Katla',
      to: 'Katla Bras-de-Fer',
      reason: 'saisie',
    },
  },
  {
    type: 'system.rules_version_migrated',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { from: 1, to: 2, note: 'montee de regles' },
  },
  {
    type: 'system.payload_upcast',
    actorKind: 'system',
    actorPlayerId: null,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { fromVersion: 1, toVersion: 2, affectedTypes: ['roll.action_resolved'] },
  },
  {
    type: 'system.note',
    actorKind: 'player',
    actorPlayerId: OWNER,
    subjectCharacterId: null,
    playSessionId: null,
    payloadVersion: 1,
    causationId: null,
    rngStream: null,
    rngDrawIndex: null,
    scope: 'table',
    recipients: null,
    payload: { text: 'reprendre ici', byPlayerId: OWNER },
  },
];

/**
 * The journal, dense from `seq` 1, one entry per catalogue type.
 *
 * `anEvent` fills the envelope; only the three fields that depend on position
 * are overridden here.
 */
export function everyEventJournal(): readonly GameEvent[] {
  return ENTRIES.map((entry, index) => {
    const seq = index + 1;
    return anEvent({
      ...entry,
      seq,
      campaignId: CAMPAIGN,
      id: anId('event', seq),
      createdAt: fixtureCreatedAt(seq),
      correlationId: `00000000-0000-4000-8000-${String(seq).padStart(12, '0')}`,
    } as Parameters<typeof anEvent>[0]);
  });
}

/** The catalogue order this fixture follows, for the test that compares them. */
export const EVERY_EVENT_TYPE = GAME_EVENT_TYPES;

// ------------------------------------------------------------- self-check

describe('the journal fixture covers the catalogue', () => {
  it('holds one entry per event type, in catalogue order', () => {
    expect(everyEventJournal().map((event) => event.type)).toEqual([...EVERY_EVENT_TYPE]);
  });

  it('is dense from one, with no gap', () => {
    expect(everyEventJournal().map((event) => event.seq)).toEqual(
      everyEventJournal().map((_event, index) => index + 1),
    );
  });
});
