/**
 * Idempotence on the client's intent identifier (03-donnees.md section 1.6).
 *
 * THREE FILES BEYOND THE SIX THE TASK SHEET NAMES, and `repositories/` holds
 * nine in all. The six named ones are the six tables of the write path; the
 * three others are:
 *
 *   - this file: idempotent intent settlement is listed under the same bullet
 *     but belongs to neither `events.ts` nor `campaigns.ts`, for exactly the
 *     reason `schema/intents.ts` got its own file;
 *   - `rows.ts`, which is not plumbing: it carries the journal's read types
 *     (`JournalEvent`, `DeliveredEvent`), `toJournalEvent`, `EVENT_COLUMNS`,
 *     and the claim that `JournalEvent` mirrors `EventEnvelopeDto` — a claim
 *     `tests/journal-mirror.test.ts` now measures instead of asserting;
 *   - `index.ts`, the barrel.
 *
 * The sheet's "Fichiers touchés" glob is `packages/db/src/repositories/**`, so
 * none of this is out of scope; an earlier version of this header under-counted
 * them, and a declaration reads as a commitment.
 *
 * WHAT IDEMPOTENCE BUYS, and it is the only serious protection there is: a
 * WebSocket reconnection replays an unacknowledged intent. Without this, the
 * dice are rolled a second time and the player gets a different outcome for an
 * action he took once. `settleIntentOnce` therefore does NOT call the decision
 * function on a replay — it returns the events already written. The test
 * counts the calls, because "no new event was produced" would also be true of
 * an implementation that rolled the dice and threw the result away.
 *
 * The insert, the decision and the settlement share ONE transaction, so a
 * committed row is never left at `received`.
 */

import type { SqliteConnection } from '../client.js';
import type { AppendableEvent } from './events.js';
import { appendEvents, readRange } from './events.js';
import type { JournalEvent } from './rows.js';

export type IntentStatus = 'received' | 'applied' | 'rejected' | 'superseded';

export interface IntentInput {
  /** UUID generated by the CLIENT. The whole idempotency story hangs here. */
  readonly id: string;
  readonly campaignId: string;
  readonly playerId: string;
  readonly type: string;
  readonly payload: unknown;
  readonly receivedAt: number;
  readonly characterId?: string | null;
}

/** What the caller decided once the intent turned out to be new. */
export type IntentDecision =
  | { readonly kind: 'apply'; readonly events: readonly AppendableEvent[] }
  | { readonly kind: 'reject'; readonly code: string; readonly detail?: string | null };

export interface IntentRejection {
  readonly code: string;
  readonly detail: string | null;
}

export interface IntentOutcome {
  readonly intentId: string;
  /** `true` when this identifier had already been settled. */
  readonly replayed: boolean;
  readonly status: IntentStatus;
  readonly events: readonly JournalEvent[];
  readonly rejection: IntentRejection | null;
}

interface IntentRow {
  readonly id: string;
  readonly campaign_id: string;
  readonly player_id: string;
  readonly status: string;
  readonly rejection_code: string | null;
  readonly rejection_detail: string | null;
  readonly first_event_seq: number | null;
  readonly last_event_seq: number | null;
}

/**
 * Raised when a known intent identifier comes back under another owner.
 *
 * `intents.id` is a PRIMARY KEY over the WHOLE table, and it is minted by the
 * client. Matching on the identifier ALONE therefore let a replay from
 * campaign B read the settlement of campaign A — and `storedOutcome` re-reads
 * the events with the STORED campaign, so the caller got another table's
 * journal, `private` events included. Measured before the fix: a second
 * `settleIntentOnce` with the same identifier, another campaign and another
 * player returned the first campaign's `private` event.
 *
 * So the match is on (identifier, campaign, player) and a mismatch is refused
 * rather than settled. The message names the identifier and nothing else: what
 * the other campaign holds is exactly what must not cross.
 */
export class IntentIdentityConflictError extends Error {
  constructor(readonly intentId: string) {
    super(`intention ${intentId} déjà enregistrée pour une autre table`);
    this.name = 'IntentIdentityConflictError';
  }
}

function storedOutcome(connection: SqliteConnection, row: IntentRow): IntentOutcome {
  const hasRange = row.first_event_seq !== null && row.last_event_seq !== null;
  return {
    intentId: row.id,
    replayed: true,
    status: row.status as IntentStatus,
    events: hasRange
      ? readRange(connection, row.campaign_id, row.first_event_seq, row.last_event_seq)
      : [],
    rejection:
      row.rejection_code === null
        ? null
        : { code: row.rejection_code, detail: row.rejection_detail },
  };
}

/**
 * Records the intent and settles it, at most once per identifier.
 *
 * `decide` is called ONLY when the identifier is new. Replaying returns the
 * stored settlement, byte for byte the same events.
 */
export function settleIntentOnce(
  connection: SqliteConnection,
  input: IntentInput,
  decide: () => IntentDecision,
): IntentOutcome {
  const run = connection.transaction((): IntentOutcome => {
    // Look, then write. `BEGIN IMMEDIATE` holds the writer lock across both,
    // and section 0.3 makes the process a single writer, so nothing can slip
    // between them. Written this way rather than as `ON CONFLICT DO NOTHING`
    // plus a re-read, which would need a non-null assertion on a row the type
    // system cannot know is there.
    const known = connection.prepare(`SELECT * FROM intents WHERE id = ?`).get(input.id) as
      IntentRow | undefined;
    if (known !== undefined) {
      if (known.campaign_id !== input.campaignId || known.player_id !== input.playerId) {
        throw new IntentIdentityConflictError(input.id);
      }
      return storedOutcome(connection, known);
    }

    connection
      .prepare(
        `INSERT INTO intents
           (id, campaign_id, player_id, character_id, type, payload_json, status, received_at)
         VALUES (?, ?, ?, ?, ?, ?, 'received', ?)`,
      )
      .run(
        input.id,
        input.campaignId,
        input.playerId,
        input.characterId ?? null,
        input.type,
        JSON.stringify(input.payload),
        input.receivedAt,
      );

    const decision = decide();

    if (decision.kind === 'reject') {
      connection
        .prepare(
          `UPDATE intents
              SET status = 'rejected', rejection_code = ?, rejection_detail = ?, settled_at = ?
            WHERE id = ?`,
        )
        .run(decision.code, decision.detail ?? null, input.receivedAt, input.id);
      return {
        intentId: input.id,
        replayed: false,
        status: 'rejected',
        events: [],
        rejection: { code: decision.code, detail: decision.detail ?? null },
      };
    }

    const appended = appendEvents(connection, {
      campaignId: input.campaignId,
      events: decision.events,
      now: input.receivedAt,
    });
    connection
      .prepare(
        `UPDATE intents
            SET status = 'applied', first_event_seq = ?, last_event_seq = ?, settled_at = ?
          WHERE id = ?`,
      )
      .run(appended.firstSeq, appended.lastSeq, input.receivedAt, input.id);

    return {
      intentId: input.id,
      replayed: false,
      status: 'applied',
      events: appended.events,
      rejection: null,
    };
  });

  return run.immediate();
}

export function getIntentStatus(
  connection: SqliteConnection,
  intentId: string,
): IntentStatus | undefined {
  const row = connection.prepare(`SELECT status FROM intents WHERE id = ?`).get(intentId) as
    { status: string } | undefined;
  return row === undefined ? undefined : (row.status as IntentStatus);
}
