/**
 * Zone A — intents and content packs (03-donnees.md section 1.6).
 *
 * `intents` is the ONLY table the client writes into (invariant 3). Its
 * primary key is the CLIENT's UUID, and that is the whole idempotency story: a
 * WebSocket reconnection that replays an unacknowledged intent lands on an
 * INSERT conflict, and the server returns the result it already computed
 * instead of rolling the dice a second time.
 *
 * Section 5.1 of the spec lists five schema files; these two tables belong to
 * neither `campaigns.ts` (they are not the campaign lifecycle) nor `ai.ts`, so
 * they get their own file. Declared as a deviation from the printed layout.
 */

import { sql } from 'drizzle-orm';
import { check, index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

import type { IntentDto } from '@for/contracts';

import { campaigns } from './campaigns.js';
import { players } from './players.js';

export const intents = sqliteTable(
  'intents',
  {
    /** UUID generated by the CLIENT. End-to-end idempotency hangs on this. */
    id: text('id').primaryKey(),
    campaignId: text('campaign_id')
      .notNull()
      .references(() => campaigns.id, { onDelete: 'restrict' }),
    playerId: text('player_id')
      .notNull()
      .references(() => players.id, { onDelete: 'restrict' }),
    characterId: text('character_id'),
    /** `move.strike`, `speech.say`, … */
    type: text('type').notNull(),
    payloadJson: text('payload_json', { mode: 'json' }).$type<IntentDto>().notNull(),
    status: text('status').notNull().default('received'),
    /** `move_in_progress`, `gauge_locked`, … Never `not_your_turn`. */
    rejectionCode: text('rejection_code'),
    rejectionDetail: text('rejection_detail'),
    firstEventSeq: integer('first_event_seq'),
    lastEventSeq: integer('last_event_seq'),
    receivedAt: integer('received_at').notNull(),
    settledAt: integer('settled_at'),
  },
  (t) => [
    index('intents_campaign_idx').on(t.campaignId, sql`${t.receivedAt} DESC`),
    index('intents_player_idx').on(t.playerId, sql`${t.receivedAt} DESC`),
    check('intents_payload_json_valid', sql`json_valid(${t.payloadJson})`),
    check(
      'intents_status_enum',
      sql`${t.status} IN ('received','applied','rejected','superseded')`,
    ),
  ],
);

/**
 * Trace of every content bundle ever loaded. Answers "which version of the
 * price table was this roll made against?".
 */
export const contentPacks = sqliteTable(
  'content_packs',
  {
    /** sha256 of the normalised bundle. */
    hash: text('hash').primaryKey(),
    /** semver of `content/manifest.json`. */
    version: text('version').notNull(),
    fileCount: integer('file_count').notNull(),
    manifestJson: text('manifest_json', { mode: 'json' }).$type<unknown>().notNull(),
    firstSeenAt: integer('first_seen_at').notNull(),
    lastSeenAt: integer('last_seen_at').notNull(),
  },
  (t) => [
    index('content_packs_version_idx').on(t.version, sql`${t.firstSeenAt} DESC`),
    check('content_packs_manifest_json_valid', sql`json_valid(${t.manifestJson})`),
  ],
);
