/**
 * `ChronicleDoc` — the compacted long memory of a campaign (02-mj-ia.md
 * section 5.2), stored in `chronicles.doc_json` (03-donnees.md section 1.5).
 *
 * This is invariant 2 made into a shape: the memory lives in the database as
 * structured state plus this document, never in the context window alone. The
 * document is regenerated by `structurer()` and re-read by the context builder
 * at every turn.
 *
 * THE CEILINGS ARE HARD, AND THEY ARE THE POINT. Their sum fits in ≈ 2 200
 * tokens; past 2 500 measured, section 5.2 replays the regeneration once with
 * a compression instruction and then prunes deterministically. A ceiling that
 * only the prompt asks for is a ceiling the model negotiates, so every one of
 * them is on the schema and a document that breaks one is refused rather than
 * truncated.
 *
 * `facts[].event_seq` IS MANDATORY, AND THAT IS THE WHOLE ANTI-DRIFT
 * MECHANISM. A fact without provenance is a fact the model invented during a
 * compaction and that every later compaction will copy forward as established
 * canon. With the sequence number, any statement can be walked back to the
 * journal line that established it — the same property `TurnProofDto` gives a
 * turn, applied to memory. It is `z.number().int()` and not `zSeq` because a
 * chronicle may cite position 0 of a campaign that has not written yet.
 *
 * `superseded_by` is nullable and never optional: a fact either points at the
 * fact that replaced it or says out loud that nothing did. An absent key would
 * read the same as "not replaced" while meaning "the model forgot the field".
 *
 * NOTHING MECHANICAL LIVES HERE. No gauge, no outcome, no die, no effect. The
 * chronicle is what the campaign REMEMBERS, and `statement` is capped at 200
 * characters with the same "one sentence, no figure" rule the `propose_lore_fact`
 * validations apply. The numbers a turn needs are in `characters` and `clocks`,
 * which are always fresh.
 */

import { z } from 'zod';

/** Quasi-immutable, two to four sentences. */
export const CHRONICLE_PREMISE_MAX = 400;

/** Section 5.2, one per list. Their sum is what fits in the budget. */
export const CHRONICLE_MAX_ARCS = 8;
export const CHRONICLE_MAX_CHARACTERS = 6;
export const CHRONICLE_MAX_NPCS = 20;
export const CHRONICLE_MAX_PLACES = 15;
export const CHRONICLE_MAX_FACTS = 60;
export const CHRONICLE_MAX_OPEN_THREADS = 12;
export const CHRONICLE_MAX_RECENT_DIGEST = 8;

/** Past this measured token count the regeneration is replayed once. */
export const CHRONICLE_TOKEN_BUDGET = 2500;

export const ChronicleArcSchema = z.object({
  id: z.string(),
  title: z.string().max(80),
  status: z.enum(['ouvert', 'dormant', 'resolu']),
  summary: z.string().max(300),
  last_event_seq: z.number().int(),
});

/** Player characters. */
export const ChronicleCharacterSchema = z.object({
  character_id: z.string(),
  name: z.string().max(60),
  one_line: z.string().max(160),
  notable_deeds: z.array(z.string().max(140)).max(3),
  current_burden: z.string().max(160),
});

export const ChronicleNpcSchema = z.object({
  npc_id: z.string(),
  name: z.string().max(60),
  role: z.string().max(60),
  status: z.enum(['vivant', 'mort', 'disparu', 'inconnu']),
  /** Standing towards the party, spelled out rather than scored. */
  stance: z.string().max(120),
  voice: z.string().max(120),
  last_seen_place: z.string().max(60),
  last_event_seq: z.number().int(),
});

export const ChroniclePlaceSchema = z.object({
  place_id: z.string(),
  name: z.string().max(60),
  one_line: z.string().max(160),
  state: z.string().max(120),
});

export const ChronicleFactSchema = z.object({
  /** Stable, never reassigned. */
  fact_id: z.string(),
  /** One sentence, no figure. */
  statement: z.string().max(200),
  entities: z.array(z.string()).max(4),
  /** PROVENANCE, MANDATORY. See the file header. */
  event_seq: z.number().int(),
  superseded_by: z.string().nullable(),
});

export const ChronicleThreadSchema = z.object({
  thread_id: z.string(),
  title: z.string().max(80),
  summary: z.string().max(200),
  opened_event_seq: z.number().int(),
  tied_to: z.string().max(60),
});

export const ChronicleDoc = z.object({
  premise: z.string().max(CHRONICLE_PREMISE_MAX),
  arcs: z.array(ChronicleArcSchema).max(CHRONICLE_MAX_ARCS),
  characters: z.array(ChronicleCharacterSchema).max(CHRONICLE_MAX_CHARACTERS),
  npcs: z.array(ChronicleNpcSchema).max(CHRONICLE_MAX_NPCS),
  places: z.array(ChroniclePlaceSchema).max(CHRONICLE_MAX_PLACES),
  facts: z.array(ChronicleFactSchema).max(CHRONICLE_MAX_FACTS),
  open_threads: z.array(ChronicleThreadSchema).max(CHRONICLE_MAX_OPEN_THREADS),
  /** Last sessions, oldest first. */
  recent_digest: z.array(z.string().max(180)).max(CHRONICLE_MAX_RECENT_DIGEST),
});

/**
 * `01-architecture.md` section 2.4 names this schema `zChronicleDoc` and
 * `02-mj-ia.md` section 5.2 names it `ChronicleDoc`. Both names point at the
 * same object rather than at two declarations — the alternative was two
 * schemas drifting apart, which is the failure this package exists to stop.
 */
export const zChronicleDoc = ChronicleDoc;

/** `structurer<ChronicleDoc>(...)` reads this type (section 5.5). */
export type ChronicleDoc = z.output<typeof ChronicleDoc>;
export type ChronicleFact = z.output<typeof ChronicleFactSchema>;
